import '../Home.css';
import '../LegalPages.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function TermsOfUse() {
  return (
    <>
      <Navbar />
      <div className="legal-hero">
        <span className="legal-eyebrow">Legal</span>
        <h1 className="legal-hero-title">Terms of Use</h1>
        <p className="legal-hero-subtitle">Last updated: May 2026</p>
      </div>

      <main className="legal-body">
        <div className="legal-container">
          <p className="legal-intro">
            These Terms of Use ("Terms") govern your access to and use of the AgriScanAI platform,
            including the mobile application, web dashboard, and any related services (collectively,
            the "Platform"), operated by Good Partners Limited ("AgriScanAI", "we", "us", or "our").
            By accessing or using the Platform you agree to be bound by these Terms.
          </p>

          <section className="legal-section">
            <h2 className="legal-section-title">1. Eligibility</h2>
            <p className="legal-text">
              You must be at least 18 years old and have the authority to enter into these Terms on
              behalf of yourself or the organisation you represent. If you are accessing the Platform
              through a partner deployment, your use is also subject to the agreement between
              AgriScanAI and your organisation.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">2. Permitted Use</h2>
            <p className="legal-text">You may use the Platform solely to:</p>
            <ul className="legal-list">
              <li>Support agricultural extension and advisory programs.</li>
              <li>Collect, manage, and analyse farmer data within an authorised deployment.</li>
              <li>Access AI-powered crop disease identification and advisory content.</li>
              <li>Generate program performance reports for internal, non-commercial use.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">3. Prohibited Conduct</h2>
            <p className="legal-text">You must not:</p>
            <ul className="legal-list">
              <li>Reverse engineer, decompile, or attempt to extract the source code of the Platform.</li>
              <li>Use automated tools to scrape, crawl, or bulk-download Platform data.</li>
              <li>Share login credentials or allow unauthorised third parties to access your account.</li>
              <li>Upload content that is unlawful, harmful, defamatory, or infringes intellectual property rights.</li>
              <li>Use the Platform to develop a competing product or service.</li>
              <li>Attempt to circumvent security controls, rate limits, or access restrictions.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">4. AI Advisory Disclaimer</h2>
            <p className="legal-text">
              The crop disease detection and advisory outputs generated by AgriScanAI are provided
              for informational and decision-support purposes only. They are <strong>not</strong> a
              substitute for professional agronomic advice. Farmers and extension agents should
              exercise independent judgement before acting on AI-generated recommendations.
              AgriScanAI makes no warranty that outputs will be accurate, complete, or suitable for
              any particular situation.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">5. Intellectual Property</h2>
            <p className="legal-text">
              All intellectual property in the Platform — including software, AI models, branding,
              and training materials — is owned by or licensed to AgriScanAI. Nothing in these
              Terms grants you ownership of Platform IP. You retain ownership of data you upload;
              you grant us a limited, non-exclusive licence to process that data to provide the
              services.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">6. Data & Privacy</h2>
            <p className="legal-text">
              Your use of the Platform is also governed by our{' '}
              <a href="/privacy-policy" className="legal-link">Privacy Policy</a>, which is
              incorporated into these Terms by reference. You are responsible for ensuring that any
              farmer data you enter has been collected with appropriate consent and in compliance
              with applicable data protection laws.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">7. Service Availability</h2>
            <p className="legal-text">
              We aim to maintain high Platform availability but do not guarantee uninterrupted
              access. We may perform maintenance, update AI models, or modify features with
              reasonable notice. Partner-level SLA commitments, where applicable, are set out in
              the relevant partnership agreement.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">8. Limitation of Liability</h2>
            <p className="legal-text">
              To the fullest extent permitted by law, AgriScanAI and its affiliates, officers, and
              employees shall not be liable for any indirect, incidental, special, consequential, or
              punitive damages arising from your use of or inability to use the Platform, including
              crop losses or economic harm resulting from reliance on AI outputs. Our total
              liability for any claim shall not exceed the fees paid by you (or your organisation)
              in the three months preceding the claim.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">9. Termination</h2>
            <p className="legal-text">
              We may suspend or terminate your access if you breach these Terms, at our sole
              discretion, with or without notice. You may stop using the Platform at any time. Upon
              termination, provisions that by their nature should survive will continue to apply,
              including Sections 5, 8, and 10.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">10. Governing Law</h2>
            <p className="legal-text">
              These Terms are governed by the laws of Kenya. Any disputes arising under or in
              connection with these Terms shall be subject to the exclusive jurisdiction of the
              courts of Nairobi, Kenya, without regard to conflict-of-law principles.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">11. Changes to These Terms</h2>
            <p className="legal-text">
              We may revise these Terms at any time. Material changes will be communicated with at
              least 14 days' notice via email or in-Platform notification. Continued use after the
              effective date constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-title">12. Contact</h2>
            <p className="legal-text">For questions about these Terms, reach out to:</p>
            <address className="legal-address">
              <strong>AgriScanAI — Legal Team</strong><br />
              Good Partners Limited<br />
              Email: <a href="mailto:legal@agriscanai.com" className="legal-link">legal@agriscanai.com</a><br />
              Website: <a href="/contact" className="legal-link">agriscanai.com/contact</a>
            </address>
          </section>
        </div>
      </main>

      <Footer />
    </>
  );
}
